export const state = {
  voices: [],
  asrJobs: [],
  ttsJobs: [],
  importCandidates: [],
  voiceSearch: "",
  selectedVoiceId: "",
  editingVoiceId: "",
  ttsUrl: "",
  activeTtsJobId: "",
  loadedTtsJobId: "",
  asrJobPollTimer: null,
  ttsJobPollTimer: null,
  realtime: {
    socket: null,
    stream: null,
    audioContext: null,
    source: null,
    processor: null,
    mute: null,
    active: false,
    targetSampleRate: 16000,
  },
};
